CREATE DATABASE [TP_CasaFotos];

CREATE TABLE [dbo].[Fotos]
(
	[id] [INT] IDENTITY(1,1) PRIMARY KEY,	
	[tamano] [VARCHAR](100) NOT NULL,
	[papel] [VARCHAR](100) NOT NULL,
	[path] [VARCHAR](MAX) NOT NULL
);

CREATE TABLE [dbo].[Pedidos]
(
	[id] [INT] IDENTITY(1,1) PRIMARY KEY,	
	[fecha] [DATE] NOT NULL DEFAULT getDate(),
	[cliente_id] [INT] NOT NULL,
	[sucursal_id] [INT] NOT NULL, 
	[foto_id] [INT] FOREIGN KEY REFERENCES Fotos(id),
	[cantidad] [INT] NOT NULL DEFAULT 1,
	[importe] [DECIMAL] NOT NULL
);

CREATE TABLE [dbo].[Clientes]
(
	[id] [INT] IDENTITY(1,1) PRIMARY KEY,	
	[nombre_apellido] [VARCHAR](MAX) NOT NULL,
	[domicilio] [VARCHAR](MAX) NOT NULL,
	[mail] [VARCHAR](100) NOT NULL
);

CREATE TABLE [dbo].[Localidades]
(
	[id] [INT] IDENTITY(1,1) NOT NULL,	
	[localidad] [VARCHAR](30) NOT NULL,
	[importe] [DECIMAL](10,2) NOT NULL
); 

CREATE TABLE [dbo].[Sucursales]
(
	[id] [INT] IDENTITY(1,1) NOT NULL,	
	[direccion] [VARCHAR](MAX) NOT NULL,
	[localidad_id] [INT] NOT NULL
); 



INSERT INTO LOCALIDADES VALUES ('SANTA FE','3500');
INSERT INTO LOCALIDADES VALUES ('SAN JUAN','4500');
INSERT INTO LOCALIDADES VALUES ('CORDOBA','3000');
INSERT INTO LOCALIDADES VALUES ('MISIONES','5000');
INSERT INTO LOCALIDADES VALUES ('PUNTA DEL ESTE','5500');
INSERT INTO LOCALIDADES VALUES ('SANTIAGO','6000');
INSERT INTO LOCALIDADES VALUES ('QUITO','10300');
INSERT INTO LOCALIDADES VALUES ('MIAMI','15000');
INSERT INTO LOCALIDADES VALUES ('RIO DE JANIERO','7900');

INSERT INTO SUCURSALES(direccion,localidad_id) VALUES('Av.Callao 400', 6);
INSERT INTO SUCURSALES(direccion,localidad_id) VALUES('Av.Lavalle 500', 7);
INSERT INTO SUCURSALES(direccion,localidad_id) VALUES('Av.Riobamba 600', 8);
INSERT INTO SUCURSALES(direccion,localidad_id) VALUES('Av.Cordoba 700', 4);

